### ISSUE TITLE
#[Whale] 설치하고 10분 동안의 불편한 점

### ISSUE THREAD

**Issue by Jrady721** [tbvjaos510/naver-webtoon-history#4]
# 불편했던 점 #1 

## 기능적인 측면
1.  웹툰 이름 클릭시, 페이지 이동과 동시에 확장프로그램 화면도 이동됨. 
>  둘 중 하나만 이동을 하게 하는 것을 추천 => 옵션으로 설정가능하게 해줬으면 함.
>  확장프로그램에서 웹툰페이지로 이동시 화면이 작아 웹툰 짤림 현상이 있음 => 
이는 모바일 화면처럼 바꾸어서 해결 가능할 것 같음.

2. 웹툰 정렬방법이 약간 수정 되었으면 함.
>  기본적으로 설정에서 정렬방식을 바꿀 수 있는데 이 부분을 웹툰목록에서 가능하게 해줬으면 함 (아마 UI 때문에 그런 것 같지만)
>  정렬 방식을 커스텀 할 수 있던데 그 부분을 정렬방식을 바꿀경우 다 초기화 되버림 => 개인적으로 커스텀 정렬 방식을 따로 할 수 있게 해줬으면 함, 저장 및 불러오기도 가능하게..

3. 최근 본 웹툰 목록에서 더보기 화살표 문제.
>  웹툰 갯수가 적을때(정확히는 모르겠지만) 클릭 시 그냥 사라지기만 함 => 웹툰을 더보기 할 필요 없을 시 안보이게 하는 것을 추천

4. 항상 그런것은 아니나 최근 웹툰 (N개) 의 갯수 표시가 30개로 보일때가 있음. (모바일 창으로 열었을때)
> 웹툰 목록도 간혈적으로 사라지기도 함.

## UI/UX 적인 측면

1. 드래그 앤 드랍 효과의 수정이 필요할듯 보임
>  이미지가 좌측으로 붙는 현상이 일어남
>  드래그 앤 드랍이 가능한지 직관적으로 볼 수 가 없음(현재 이미지에만 cursor:pointer가 적용됨) => hover 이벤트로 밝기 변화 혹은 cursor:pointer 효과를 주면 좋겠음

2.  최근 본 웹툰 페이지의 좌우 패딩을 줬으면 함.
> 다른 두 개의 페이지는 좌 우 패딩이 존재하는데 최근 본 웹툰 페이지는 존재하지 않아 일관적이지 않음.
> 그외 패딩 적절히 활용 해줬으면 함. <= 지금도 디자인 충분히 괜찮지만 조금 수정하는것도 좋을 것 같음
> 그리고 테이블 각각의 td요소 마다 수직중앙 정렬 및 수평중앙 정렬 도 해줬으면 함.
> table hover시 tr 전체적으로 일차적으로 효과를 주고 (웹툰 이름, 회차)별로 따로 또 한번 주는 것을 추천. > 시간은 따로 클릭해서 효과가 있는 것도 아닌데 hover 이벤트가 있는것도 수정해줬으면 함.

3. 체크 박스 및 라디오 박스의 체크 시 체크부분이 왼쪽으로 쏠려보이는 현상이 있음 => 원래 그런 UI 라이브러리? 인것 같음.
> 체크를 할떄 그 부분만 클릭이 아니라 그거와 연관된 텍스트 클릭시에도 체크 되었으면 함 (label를 이용)

## 기타
1.  최근 본 웹툰 페이지에서 상단 부분 제목?이 최근 웹툰(N개)이런식으로 되어있음. 
> 최근 본 웹툰으로 수정하는 게 좋지 않을까 생각해봄

2. 도움말 탭도 있으면 좋겠음. 사용 방법에 대한 좀 더 직관적이거나 효과적으로 알려줬으면 함.
> hover 이벤트나 기타 애니메이션으로 이것은 이런식으로 작동함을 _직관적_으로 알수 있음 좋겠음

3. 웹툰 DB나 위키 같은것을 추가하면 좋겠다고 생각이 듬
> 개인적이지만 필자는 가끔 웹툰 DB나 위키에서 검색하면서 노는걸 좋아함

4. 페이지가 바뀌어도 웹툰 확장프로그램이 유지되었으면 함. 
> 웹 서핑하다가도 웹툰 up을 보고 볼 수 있었음 좋겠음 (새 탭열기 사라지지 않는데 그것을 응용하면 어떨까 생각해봄)

**Comment by tbvjaos510** [comment]
v2.3버전과 v2.4버전에 걸쳐 수정될 예정입니다. 감사합니다!
